# Generated by Django 5.1.7 on 2025-04-09 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_category_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='stock',
        ),
    ]
